spring:
  datasource:
    url: jdbc:sqlite::resource:db/test.db
    driver-class-name: org.sqlite.JDBC

resid:
  host: 127.0.0.1
  port: 6379
  timeout: 6000ms

mybatis:
  mapperLocations: classpath:mapper/*.xml

mybatis-plus:
  configuration:
      jdbc-type-for-null: 'null'